/* log2.c generated by valac 0.12.0, the Vala compiler
 * generated from log2.vala, do not modify */


#include <glib.h>
#include <glib-object.h>




void truc (void);


void truc (void) {
	g_print ("aa");
}



